when:
  event: tag
  ref: refs/tags/v*

steps:
  release:
    image: tensorush/ziglang:latest
    pull: true

    environment:
      MINISIGN_SECRET_KEY:
        from_secret: MINISIGN_SECRET_KEY
      MINISIGN_PUBLIC_KEY:
        from_secret: MINISIGN_PUBLIC_KEY

    commands: |
      echo "Set up minisign"
      apk --no-cache add curl
      curl -L https://github.com/jedisct1/minisign/releases/latest/download/minisign-0.12-linux.tar.gz -o minisign.tar.gz
      tar -xf minisign.tar.gz
      export "PATH=$CI_WORKSPACE/minisign-linux/x86_64/:$PATH"

      echo "Run \`release\` step"
      apk --no-cache add xz zip
      zig build release

      echo "Sign release binaries"
      echo "$MINISIGN_SECRET_KEY" > minisign.key
      minisign -S -s minisign.key -m zig-out/release/*
      echo "$MINISIGN_PUBLIC_KEY" > zig-out/release/minisign.pub
      rm minisign.key

  publish:
    image: woodpeckerci/plugin-release

    settings:
      api_key:
        from_secret: TOKEN
      files: zig-out/release/*
      note: |
        Archived binary files can be verified as follows:
        ```sh
        minisign -Vm <archive> -p minisign.pub
        ```
